Ef/v2/albert
EricFillion/happy-transformer pull request #168
Opened 2021-01-09 21:32 UTC by EricFillion

**Changes**

- Added ALBERT functionality for TC, QA and WP along with test cases 
- Added BERT test cases for TC, QA and WP
- Added a public variable called "model_type_error" to HappyTransformer. 

**Testing**
- tests/test_qa.py
- tests/test_tc.py
- tests/test_wp.py

2021-01-09 22:29 UTC, ted537 commented
Now that we have 3 separate models, can we codify the lookup processor somewhere to reduce the `if elif` business?

Something like

```
# model_parts.py
# using actual class here because namedtuples defaults support is meh
class ModelParts:
    def __init__(self,tokenizer, seq=None, qa=None, mlm=None, etc):
       self.tokenizer = tokenizer
       # more boring init stuff

MODEL_PARTS = {
    'bert':ModelParts(BertTokenizerFast,seq=BertForSequenceClassification)
}

# usage
from model_parts import MODEL_PARTS
parts = model_parts['BERT']
model = model_parts.seq.from_pretrained(model_name)
```

2021-01-09 22:29 UTC, ted537 requested changes
see other comment

2021-01-09 22:37 UTC, EricFillion commented
> Now that we have 3 separate models, can we codify the lookup processor somewhere to reduce the `if elif` business?
> 
> Something like
> 
> ```
> # model_parts.py
> # using actual class here because namedtuples defaults support is meh
> class ModelParts:
>     def __init__(self,tokenizer, seq=None, qa=None, mlm=None, etc):
>        self.tokenizer = tokenizer
>        # more boring init stuff
> 
> MODEL_PARTS = {
>     'bert':ModelParts(BertTokenizerFast,seq=BertForSequenceClassification)
> }
> 
> # usage
> from model_parts import MODEL_PARTS
> parts = model_parts['BERT']
> model = model_parts.seq.from_pretrained(model_name)
> ```

We can look into doing something like this when we have more models. For now it's pretty simple and concise just to use if and elif statements, but I agree we should eventually make a transition

2021-01-09 22:42 UTC, ted537 requested changes

2021-01-09 22:42 UTC, ted537 commented on tests/test_tc.py
> +    answer = [[{'label': 'LABEL_1', 'score': 0.9995690584182739}], [{'label': 'LABEL_0', 'score': 0.9981549382209778}], [{'label': 'LABEL_0', 'score': 0.9965545535087585}], [{'label': 'LABEL_1', 'sco
line breaks are cool

2021-01-09 22:42 UTC, ted537 commented on tests/test_qa.py
> +    assert after_loss < before_loss
good test i like

2021-01-10 01:32 UTC, ted537 commented on tests/test_tc.py
> +    answer = [[{'label': 'LABEL_1', 'score': 0.9995690584182739}], [{'label': 'LABEL_0', 'score': 0.9981549382209778}], [{'label': 'LABEL_0', 'score': 0.9965545535087585}], [{'label': 'LABEL_1', 'sco
By this I mean there are some ridiculously long lines in here. the list at 111 could be spread out vertically

2021-01-10 02:02 UTC, ted537 approved these changes

2021-01-10 02:11 UTC, merged