Add support for bad_words Issue:#246
EricFillion/happy-transformer pull request #258
Opened 2021-08-30 11:10 UTC by ujwal-narayan

Added support for bad_word_ids as discussed in Issue#246 
- Modified GENSettings to allow users to provide a list of bad words/phrases
- Modified generate_text in `happy-transformer/happy_generation.py` 
- Added a test_case `test_bad_words` in `tests/test_gen.py`
- Updated documentation and examples  in `docs/1-text-generation/3-settings.md`

2021-08-31 00:03 UTC, EricFillion requested changes
Thanks for adding this feature! I really appreciate how you put in effort to write in-depth tests and to update the documentation. Here are some suggestions

2021-08-31 05:27 UTC, ujwal-narayan commented on happytransformer/happy_generation.py
> +            bad_words_ids = [self.tokenizer(" "+phrase.strip()).input_ids for phrase in args.bad_words]
In the tokenizer, a word occuring at  the start of the sentence is treated differently from  a word occuring in the middle of the sentence.  So without the white space, the first word will have a different word id and thus won't actually be prohibited from generation. 
```python
>>> from transformers import GPT2TokenizerFast
>>> tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
>>> tokenizer("Hello world")['input_ids']
[15496, 995]
>>> tokenizer(" Hello world")['input_ids']
[18435, 995]
```

With the regular slow tokenization, you can have a parameter`add_prefix_space=True` at inference time to essentially do this. But with the FastTokenizer variant, you would need to initialize the tokenizer with the `add_prefix_space=True`, and thus you can't do it at inference time. 

I wasn't keen on changing the instantiation of the tokenizer as I didn't know what else would change with it, so I manually added the prefix space.

2021-08-31 05:53 UTC, ujwal-narayan commented
Thank you so much for your feedback!  I've  updated the pull request with the requested changes :)

2021-09-02 01:54 UTC, EricFillion commented
Thanks for adding this feature! I'll create a new release within a week.

2021-09-02 01:54 UTC, merged

2021-09-02 01:56 UTC, EricFillion commented on happytransformer/happy_generation.py
> +            bad_words_ids = [self.tokenizer(" "+phrase.strip()).input_ids for phrase in args.bad_words]
Great explanation! What you did sounds reasonable